// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOdGj-VFehs7aUo-x4U4JTbZ2ruJSI7I',
    appId: '1:495317353925:web:dd221be6c423931d0077ac',
    messagingSenderId: '495317353925',
    projectId: 'goldapp-df4bc',
    authDomain: 'goldapp-df4bc.firebaseapp.com',
    storageBucket: 'goldapp-df4bc.firebasestorage.app',
    measurementId: 'G-3RYJBKFXPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVkLwvkfmOcicoGJbTROVQMUblPpMUf1Q',
    appId: '1:495317353925:android:cb5843d08185a7f80077ac',
    messagingSenderId: '495317353925',
    projectId: 'goldapp-df4bc',
    storageBucket: 'goldapp-df4bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnqWh1n8p13z2DY4ta7kTyWhsddkhebRw',
    appId: '1:495317353925:ios:1f2bf49bf07d24900077ac',
    messagingSenderId: '495317353925',
    projectId: 'goldapp-df4bc',
    storageBucket: 'goldapp-df4bc.firebasestorage.app',
    iosBundleId: 'com.example.goldapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnqWh1n8p13z2DY4ta7kTyWhsddkhebRw',
    appId: '1:495317353925:ios:1f2bf49bf07d24900077ac',
    messagingSenderId: '495317353925',
    projectId: 'goldapp-df4bc',
    storageBucket: 'goldapp-df4bc.firebasestorage.app',
    iosBundleId: 'com.example.goldapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCOdGj-VFehs7aUo-x4U4JTbZ2ruJSI7I',
    appId: '1:495317353925:web:022c2eeb003c91cc0077ac',
    messagingSenderId: '495317353925',
    projectId: 'goldapp-df4bc',
    authDomain: 'goldapp-df4bc.firebaseapp.com',
    storageBucket: 'goldapp-df4bc.firebasestorage.app',
    measurementId: 'G-V18G8DYDBN',
  );
}
